package workflow

import (
	"bytes"
	"encoding/json"
	"fmt"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
	"project-framework/internal/jsonvalue"
)

// ParseJSONDefinition decodes a draft with the same binding and policy rules as
// YAML definitions. Explicit zero policies and mixed binding fields are errors;
// omitted policies retain their normal compiler defaults. Numbers stay exact.
func ParseJSONDefinition(data []byte) (Definition, error) {
	if len(data) > MaxFileBytes {
		return Definition{}, fmt.Errorf("definition exceeds 1 MiB limit")
	}
	value, err := jsonvalue.Parse(data)
	if err != nil {
		return Definition{}, err
	}
	object, ok := value.(map[string]any)
	if !ok {
		return Definition{}, fmt.Errorf("definition must be an object")
	}
	if err := checkDraftFields(object); err != nil {
		return Definition{}, err
	}
	if err := checkYAMLBindingsAndPolicies(jsonYAMLNode(object)); err != nil {
		return Definition{}, fmt.Errorf("%s", strings.ReplaceAll(err.Error(), " (line 0)", ""))
	}
	var definition Definition
	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	decoder.UseNumber()
	if err := decoder.Decode(&definition); err != nil {
		return Definition{}, fmt.Errorf("definition: %w", err)
	}
	return definition, nil
}

func checkDraftFields(object map[string]any) error {
	if err := checkObjectFields(object, "definition", []string{"apiVersion", "workflowId", "definitionVersion", "title", "inputSchema", "outputSchema", "nodes", "outputs"}); err != nil {
		return err
	}
	if nodes, ok := object["nodes"].([]any); ok {
		for index, value := range nodes {
			node, ok := value.(map[string]any)
			if !ok {
				return fmt.Errorf("nodes[%d]: must be an object", index)
			}
			path := fmt.Sprintf("nodes[%d]", index)
			if err := checkObjectFields(node, path, []string{"id", "type", "typeVersion", "title", "config", "inputs", "dependsOn", "timeoutMs", "retry"}); err != nil {
				return err
			}
			if retry, exists := node["retry"]; exists {
				policy, ok := retry.(map[string]any)
				if !ok {
					return fmt.Errorf("%s.retry: must be an object", path)
				}
				if err := checkObjectFields(policy, path+".retry", []string{"maxAttempts", "backoffMs"}); err != nil {
					return err
				}
			}
		}
	}
	return nil
}

func checkObjectFields(object map[string]any, path string, allowed []string) error {
	for _, key := range sortedKeys(object) {
		if !contains(allowed, key) {
			return fmt.Errorf("%s.%s: unknown field", path, key)
		}
	}
	return nil
}

// MarshalDefinitionYAML exports a deterministic, two-space-indented definition.
// json.Number values are emitted as numeric YAML scalars, never quoted strings.
// This function exports data only; use Compile first to validate executable drafts.
func MarshalDefinitionYAML(definition Definition) ([]byte, error) {
	data, err := json.Marshal(definition)
	if err != nil {
		return nil, fmt.Errorf("encode definition: %w", err)
	}
	value, err := jsonvalue.Parse(data)
	if err != nil {
		return nil, err
	}
	var output bytes.Buffer
	encoder := yaml.NewEncoder(&output)
	encoder.SetIndent(2)
	if err := encoder.Encode(jsonYAMLNode(value)); err != nil {
		return nil, fmt.Errorf("encode YAML: %w", err)
	}
	if err := encoder.Close(); err != nil {
		return nil, err
	}
	return output.Bytes(), nil
}

func jsonYAMLNode(value any) *yaml.Node {
	switch value := value.(type) {
	case map[string]any:
		node := &yaml.Node{Kind: yaml.MappingNode, Tag: "!!map"}
		keys := make([]string, 0, len(value))
		for key := range value {
			keys = append(keys, key)
		}
		sort.Strings(keys)
		for _, key := range keys {
			node.Content = append(node.Content, jsonYAMLNode(key), jsonYAMLNode(value[key]))
		}
		return node
	case []any:
		node := &yaml.Node{Kind: yaml.SequenceNode, Tag: "!!seq"}
		for _, item := range value {
			node.Content = append(node.Content, jsonYAMLNode(item))
		}
		return node
	case json.Number:
		tag := "!!int"
		if strings.ContainsAny(string(value), ".eE") {
			tag = "!!float"
		}
		return &yaml.Node{Kind: yaml.ScalarNode, Tag: tag, Value: string(value)}
	case string:
		return &yaml.Node{Kind: yaml.ScalarNode, Tag: "!!str", Value: value}
	case bool:
		return &yaml.Node{Kind: yaml.ScalarNode, Tag: "!!bool", Value: fmt.Sprint(value)}
	default:
		return &yaml.Node{Kind: yaml.ScalarNode, Tag: "!!null", Value: "null"}
	}
}

// yamlJSONValue preserves decimal spellings generated by draft export. Decoding
// a complete YAML document into interface{} would otherwise round decimals and
// large integers through float64 before the JSON schema validator sees them.
func yamlJSONValue(node *yaml.Node) (any, error) {
	switch node.Kind {
	case yaml.MappingNode:
		object := make(map[string]any, len(node.Content)/2)
		for index := 0; index < len(node.Content); index += 2 {
			value, err := yamlJSONValue(node.Content[index+1])
			if err != nil {
				return nil, err
			}
			object[node.Content[index].Value] = value
		}
		return object, nil
	case yaml.SequenceNode:
		array := make([]any, 0, len(node.Content))
		for _, item := range node.Content {
			value, err := yamlJSONValue(item)
			if err != nil {
				return nil, err
			}
			array = append(array, value)
		}
		return array, nil
	case yaml.ScalarNode:
		if node.Tag == "!!int" || node.Tag == "!!float" {
			value, err := jsonvalue.Parse([]byte(node.Value))
			if number, ok := value.(json.Number); err == nil && ok {
				return number, nil
			}
		}
	}
	var value any
	if err := node.Decode(&value); err != nil {
		return nil, err
	}
	return value, nil
}
